#!/usr/bin/env bash
#script that creates the AUTHORS file
set -e

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOTDIR="$(cd "${SCRIPTDIR}/.." && pwd)"

set -x

cat > "${ROOTDIR}/AUTHORS" <<- EOF
	# file @generated by hack/generate-authors.sh. DO NOT EDIT
	# This file lists all contributors to the repo.
	# See hack/generate-authors.sh to make modifications.

	$(git -C "$ROOTDIR" log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf)
EOF
